### ISSUE TITLE
Move C++ code to another repository

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1105]
It was my understanding during the last FLINT Friday that we in some regard should move all C++ code to another repository. I think this is a good idea, but I have no idea on how to accomplish this. I mean, this means that someone has to be a maintainer for it.

If no maintainer can be found, I would propose to just drop every C++ related file to a tarball that can be downloaded on flintlib.org.

**Comment by wbhart** [comment]
I think we have to keep it running ourselves. This doesn't mean extending it or wrapping additional functions. But we should track down any bugs that emerge and make any build system changes required to keep it running.

**Comment by albinahlback** [comment]
@fredrik-johansson do you have any idea if the C++ code is still working? Is the interface complete (in the sense that it covers most of the user-intended functions and types)?

If not, I would once again propose to remove it. We currently do not test it, and have no maintainer of it.

**Comment by fredrik-johansson** [comment]
It's not working because it wraps lots of functions which have been deleted. Getting it working again should just be a matter of deleting those wrappers.

I created https://github.com/flintlib/flintxx which is currently empty. I propose moving the code there and leaving it to someone who actually cares about it to un-bit-rot it. Of course it will need a makefile and so on.

**Comment by edgarcosta** [comment]
It has been moved, the `un-bit-rot it` is still ongoing
I propose we close this issue.
