### ISSUE TITLE
Move user-intended types to a separate header

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1151]
...that will be included in `flint.h`.

Should drastically reduce overhead for many headers (will not really matter for compiling FLINT, but for libraries using FLINT it will).

**Comment by monien** [comment]
It would be good if the general file structure of flint stabilises at some point in the near future. I have written a complete wrapper for the FLINT library for Haskell and keeping up with the changes in structure and renaming files has been a challenge ... . I have not released my wrapper because of this ... .

**Comment by albinahlback** [comment]
If I remember it correctly, I solved it this spring by implementing `XXX_types.h`, such as `fmpz_types.h`. Hence, with this one does not need to include `fmpz_poly.h` (a pretty large header) in order to define `fmpz_poly_t`. Moreover, the most "basic" types are defined in `flint.h`, namely `nmod_t`, `fmpz_t` and `fmpq_t`.
