### ISSUE TITLE
Local optimizations and default optimization level

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1323]
Currently I'm looking at `_nmod_vec_add`, and, as one could expect, it really benefits from both compiling with `-O3` and `-mavx[2/512]`, at least on GCC 12.2.1. `-O2 -mavx[2/512]` and `-O3 -mavx[2/512]` are not enough to give vectorized optimizations.

I will try to check which functions do benefit from `-O3 -mavx[2/512]` and set local optimization levels for these ones.

**Comment by fredrik-johansson** [comment]
To benefit maximally from vectorization, we'll ultimately need both
* different representations for different-sized moduli
* hand-coded algorithms using vector intrinsics

It would be good to get Dan's FFT up and running sooner than later since some of the code there should be reusable (machine_vectors.h, crt_helpers.h).

Anyway, as a first step towards FLINT-AVX, it's certainly interesting to see what the compiler can do alone with the right optimization flags.

**Comment by albinahlback** [comment]
>     * different representations for different-sized moduli

Definitely, but how is the question. I suppose one could initialize a size 2 array in each function that calls such functions, and one could call the proper function via something like
```
array_of_nmod_add[mod.n != 0](my, arg, ume, nts)
```
but that would be kind of tedious to do throughout the repository. 

>     * hand-coded algorithms using vector intrinsics

What do you mean, specifically? I do not think using intrinsics will help us, it is usually easier to guide the compiler to generate the right functions (such as utilizing builtins).

> Anyway, as a first step towards FLINT-AVX, it's certainly interesting to see what the compiler can do alone with the right optimization flags.

I'll be writing some profilers to try to see how performance changes.

**Comment by fredrik-johansson** [comment]
> Definitely, but how is the question. I suppose one could initialize a size 2 array in each function that calls such functions, and one could call the proper function via something like

I wouldn't try to change the existing ``nmod`` type but rather add separate implementations. Thanks to ``gr`` this is now easy: see the ``nmod8`` type for example. Indeed, it should be possible to get much bigger speedups for ``nmod8`` than for ``nmod``, using vectorized 8-bit and 16-bit integer operations.

> What do you mean, specifically?

You can look at how the FFT does modular arithmetic:
* 50-bit primes so that ``float64`` can be used
* delayed reductions in the inner operations (in the FFT, the "butterflies"; in most other functions this will be things like dot products)

A lot of things need to be hand-written since the compiler does not know how to exploit a precomputed approximate inverse, how much work can be done without reductions, etc.

**Comment by albinahlback** [comment]
Yes, thought I mentioned GR, but apparently not. Is your idea to add nmod16 and nmod32 as well?

Just a thought: do people use modular arithmetic with bytes? And is performance key there?

**Comment by albinahlback** [comment]
It would be nice if we could assume that the modulus is smaller than a quarter of the largest unsigned value of the primitive type. So for `nmod_t` it would be `\floor{(2^{64} - 1) / 4} = 2^{62} - 1`. This is because AVX2 does not support unsigned integer comparisons, it is only available with AVX512. As such, one has to make an extra addition when checking if a sum is larger than the modulus. So if we could skip this extra addition it would be nice.

**Comment by albinahlback** [comment]
Results from profiler when creating a new function `_nmod_vec_add_fast`, that contains no if statement and sets the local optimization level to `-O3`:
```
            _nmod_vec_add       _nmod_vec_add_fast
                    1.475                    1.443     3 mod bits, 1 len
                    0.478                    0.345     3 mod bits, 9 len
                    0.411                    0.196     3 mod bits, 25 len
                    0.386                    0.155     3 mod bits, 57 len
                    0.370                    0.139     3 mod bits, 121 len
                    0.377                    0.139     3 mod bits, 249 len
                    0.357                    0.130     3 mod bits, 505 len
                    0.399                    0.186     3 mod bits, 1017 len
                    1.474                    1.443     23 mod bits, 1 len
                    0.478                    0.346     23 mod bits, 9 len
                    0.413                    0.196     23 mod bits, 25 len
                    0.384                    0.154     23 mod bits, 57 len
                    0.370                    0.139     23 mod bits, 121 len
                    0.376                    0.127     23 mod bits, 249 len
                    0.357                    0.132     23 mod bits, 505 len
                    0.397                    0.182     23 mod bits, 1017 len
                    1.474                    1.442     43 mod bits, 1 len
                    0.478                    0.346     43 mod bits, 9 len
                    0.410                    0.196     43 mod bits, 25 len
                    0.386                    0.155     43 mod bits, 57 len
                    0.370                    0.139     43 mod bits, 121 len
                    0.376                    0.140     43 mod bits, 249 len
                    0.357                    0.131     43 mod bits, 505 len
                    0.405                    0.191     43 mod bits, 1017 len
                    1.474                    1.442     63 mod bits, 1 len
                    0.478                    0.346     63 mod bits, 9 len
                    0.411                    0.196     63 mod bits, 25 len
                    0.382                    0.155     63 mod bits, 57 len
                    0.366                    0.139     63 mod bits, 121 len
                    0.375                    0.128     63 mod bits, 249 len
                    0.357                    0.126     63 mod bits, 505 len
                    0.405                    0.189     63 mod bits, 1017 len
```
This is not a small gain. I configured with `./configure --enable-avx2 --disable-shared` in order to show that `-O3` helps very much here. I compiled `nmod_vec_add_fast` just like any other source function in FLINT and simply declared it in the profiler.

Note: I believe the result from 63 bits are not correct as I only used `_nmod_add` inside that function.

**Comment by albinahlback** [comment]
I also think that `-Os` and `-Oz` are important flags, which, in my experience, is used for larger "sporadic" functions.

**Comment by fredrik-johansson** [comment]
> Yes, thought I mentioned GR, but apparently not. Is your idea to add nmod16 and nmod32 as well?
> 
> Just a thought: do people use modular arithmetic with bytes? And is performance key there?

Yeah, I imagine eventually having ``nmod8``, ``nmod16``, ``nmod32``, ``nmod64`` and maybe even an ``nmod128``, plus types based on ``float`` and ``double``.

Mostly these would be for internal use and accessible via ``gr`` interfaces, but you could have a ``fq_default``-like wrapper type.

> Just a thought: do people use modular arithmetic with bytes? And is performance key there?

This all depends on the application.

Our main use for modular arithmetic is multimodular algorithms, where we have the freedom to choose moduli that give the best performance. Classically, without vectorization, this usually means choosing full 64-bit primes to minimize the number of modular computations (each costs overhead to set up and execute, and then there are the modular reduction and CRT costs which can be significant). However, slightly smaller primes, ~60 bits, can be better as they allow for faster dot products.

On modern CPUs with poorly vectorized 64-bit integer math and well-vectorized 64-bit floating-point math (including exact FMAs), it can be significantly faster to work with ``double`` modular arithmetic; see Dan's FFT for proof of this.

However, there are also many situations where we want to obtain structural information rather than extracting as many bits as possible, for example when factoring polynomials or checking if a matrix is invertible. In such cases, we typically want to choose small (1-byte or 2-byte) initial primes.

Having specialized representations for such moduli allows for better vectorization and better cache locality. There are also applications where overall memory consumption is an issue, and where a 2x or 4x memory reduction can make all the difference.

There are also applications where the modulus is fixed by the mathematical problem and not something we can choose freely, and then of course we want to have efficient arithmetic for each such case.

**Comment by fredrik-johansson** [comment]
> I also think that `-Os` and `-Oz` are important flags, which, in my experience, is used for larger "sporadic" functions.

Sure, though there are perhaps not that many such functions in the library code itself. Something like ``fexpr/write_latex.c`` comes to mind.

**Comment by albinahlback** [comment]
I will close this one.
