### ISSUE TITLE
Build a fast Flint by default

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#1357]
We should arguably build with AVX2/Neon instructions + ``fft_small`` enabled by default when the machine supports it.

Likewise, BLAS should arguably be enabled by default (if ``configure`` detects it).

**Comment by AndreasEnge** [comment]
For distributions, it would be nice if a "fat binary" could be created as for GMP:
   https://gmplib.org/manual/Build-Options
"Fat binary, --enable-fat
    Using --enable-fat selects a “fat binary” build on x86, where optimized low level subroutines are chosen at runtime according to the CPU detected. This means more code, but gives good performance on all x86 chips. (This option might become available for more architectures in the future.)"

This would result in a binary that works everywhere, yet contains optimised implementations, regardless of the build machine. Otherwise distributions would be forced to disable optimisations depending on CPU subarchitectures.

**Comment by fredrik-johansson** [comment]
Note: I tried to make AVX2 detection automatic on the [autovx](https://github.com/flintlib/flint2/tree/autovx) branch but this is currently failing.

**Comment by mezzarobba** [comment]
> Note: I tried to make AVX2 detection automatic on the [autovx](https://github.com/flintlib/flint2/tree/autovx) branch but this is currently failing.

I don't know exactly what you mean by that, but this might be useful: https://www.gnu.org/software/autoconf-archive/ax_ext.html

**Comment by albinahlback** [comment]
I think the best option is to enable `-march=native` whenever `--host` and `CFLAGS` is not set.

**Comment by fredrik-johansson** [comment]
Yes, that makes sense. Also ``-O3``.

**Comment by albinahlback** [comment]
I will fix this some time soon.
