### ISSUE TITLE
fft_small without AVX2

### ISSUE THREAD

**Issue by edgarcosta** [flintlib/flint#1465]
It is perhaps worthwhile to write fft_small without relying on AVX2 calls, and use [`target_clones`](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-target_005fclones-function-attribute) to let the compiler do its own optmization

I wrote a small piece code to compare the speed of some AVX2 instructions against non-optimized code compiled with `-mavx2`, and I found the time difference negligible.

```
# include "machine_vectors.h"
# include "d_vec.h"
#include <assert.h>



double dot_plain(double *a, double* b, const size_t n) {
    double res = 0;
    for(size_t i=0; i < n; ++i)
        res += a[i] * b[i];
    return res;
}

double dot_4d(double *a, double *b, const size_t n) {
    double res = 0;
    assert( n%4 == 0 );
    for(size_t i=0; i < n; i += 4) {
        double tmp[4];
        vec4d_store(tmp, vec4d_mul(vec4d_load_unaligned(a + i), vec4d_load_unaligned(b + i)));
        for(size_t j=0; j < 4;  ++j)
            res += tmp[j];
    }
    return res;
}

int main(int c, char* argv[]) {
    size_t len = atoi(argv[1]);
    size_t mul = atoi(argv[2]);
    size_t target = atoi(argv[3]);

    double (*dot)(double *a, double *b, const size_t n) = (target == 0) ? &dot_plain : &dot_4d;
    FLINT_TEST_INIT(state);

    double *a, *b;
    a = _d_vec_init(len);
    b = _d_vec_init(len);
    _d_vec_randtest(a, state, len, 0, 0);
    _d_vec_randtest(b, state, len, 0, 0);

    double tmp = 0;
    for(size_t i = 0; i < mul * 10000; ++i) {
        tmp += (*dot)(a, b, 0);
    }
    _d_vec_clear(a);
    _d_vec_clear(b);
    if ( tmp > 0 )
        tmp *= -1;
    FLINT_TEST_CLEANUP(state);
    return tmp > 0? 0: 1;
}
```

**Comment by albinahlback** [comment]
So this issue is not about possibilities to use `fft_small` without AVX2 instructions, but rather to use it without intrinsics?

**Comment by vneiger** [comment]
Is this issue still "on", and has anyone made more experiments towards this?

I would not be surprised if at many places, the explicit vectorization in `fft_small` produces significantly better performance than some compiler's vectorization would. But this is a pure guess, I have not made direct experiments on the `fft_small` code.

However I can comment on my recent experience with additions to `nmod_dot_product`. Both `clang` and `gcc` indeed produce very good code when it comes to vectorizing "simple" things, e.g. a loop for dot product on `int`s like the example above. But as soon as the vectorization becomes less trivial, it seems quite more reliable to use intrinsics rather than hope the compiler will do what we want.

As an example, when I let the compiler vectorize this (and many variants hoping to make the compiler find a fast vectorized version)
https://github.com/flintlib/flint/blob/449694569163502fc31d66ac5363724969c9e756/src/nmod_vec.h#L537-L553
I got a slight acceleration, but this was still substantially slower than vectorizing explicitly as in
https://github.com/flintlib/flint/blob/449694569163502fc31d66ac5363724969c9e756/src/nmod_vec/dot.c#L112-L129
And here the code with explicit vectorization does not seem difficult to deduce (hardly more difficult than for the int dot product), but apparently gcc-14 and clang-18 are not so good in that case.

**Comment by albinahlback** [comment]
> Is this issue still "on", and has anyone made more experiments towards this?

To my knowledge, no one is currently working on it.

> ...
> And here the code with explicit vectorization does not seem difficult to deduce (hardly more difficult than for the int dot product), but apparently gcc-14 and clang-18 are not so good in that case.

Yeah, I hear you. I have found compilers very hard to understand performance-wise. Sometimes, with the right flags and right instruction sequence, you get (close to) the optimal sequence of assembly instructions. However, as you imply, it is sometimes way off.

**Comment by edgarcosta** [comment]
When writing this kind of code, there is always a cost-benefit analysis when to do it.
Many of you enjoy these things, and I do not, so our cost function of writing it is very different.
However, I would argue that our cost function of maintenance should be similar, as it is hard to predict who will be around to fix or change things as necessary.
Furthermore, many of the benefits of trying to help the compiler go away in a couple of years as the compilers keep improving.
All this makes me an advocate for having simpler code and letting the compiler have fun with it. 

All this is to say I opened the issue, but I also do not maintain the `fft_small` code, so feel free to close it. 😄

**Comment by albinahlback** [comment]
> Furthermore, many of the benefits of trying to help the compiler go away in a couple of years as the compilers keep improving. All this makes me an advocate for having simpler code and letting the compiler have fun with it.

I'm not so sure about this. I would say that it depends on what you are looking for. If we care about getting close to the optimal routine, I would still say that a lot of cases you have to hard code. In the end, there is so many aspects to take into consideration, such as
- Can the compiler make certain assumptions? (`__builtin_unreachable` can help here, so does `restrict`)
- What code size are you willing to have?
- How long are you willing to wait for a compilation? (A superoptimizer is very slow)
- Does the compiler know about all features of the CPU? (Take Apple's AMX for instance, which remains undocumented AFAIK)

I do agree that one has to make a cost-benefit analysis on this. However, hopefully in the future we can get some compiler that is good with multiple-precision arithmetic. :-)

**Comment by vneiger** [comment]
Code size is indeed one of the points here; in my experiments I got significantly larger assembly size when I was letting the compiler vectorize itself (even when it succeeded in having something rather fast).

> If we care about getting close to the optimal routine, I would still say that a lot of cases you have to hard code.

I agree with this. To add to the four listed aspects, we sometimes use nontrivial "tricks" or knowledge about what we are computing with, that I doubt compilers will be good at discovering/using themselves anytime soon (if at all).

Let's consider `nmod` things, where computations are done modulo some 64 bit integer. There are often different strategies depending on the bitsize of the modulus:
- in order to avoid doing too frequent modular reductions, which slow everything down (in both scalar and vectorized worlds), so categories like "quite smaller than 32 bits", "less than 32 bits", "quite smaller than 64 bits", "less than 64 bits"
- in order to exploit floating point operations (e.g. avx512's fma) when available and relevant, in which case we can have categories like "less than 26 bits" or "less than 52 bits" due to floating point constraints.

Even excluding vectorization aspects, the compiler would e.g. not delay modular reductions depending on how far the modulus is from 32 bit or 64 bits (you can waste a factor more than 5 due to this). And I don't see how it could: for example, it does not know that the "ulong"'s we are computing with are actually less than the modulus, and it does not know how many ulong's can be added before overflowing. For something simple such as dot products over `nmod`'s, flint had already 4 implementations due to this kind of things, and now with recent changes to incorporate avx2 and delayed reductions, it has 7 or 8 different implementations. Most of them are because the compiler was not getting close to the performance we have now. I don't really see how the type of compilers we use could handle this much better than it already does (without requiring us to add lots of information and cases in the code to guide the compiler, but is it then not simpler to follow our current approach?).

For vectorization specifically, I observed quite mixed results, as highlighted in the example above: maybe one major issue behind this is that vectorization (avx2 and avx512) does not provide 64-bit integer multiplication. Again, if doing a dot product of two vectors of length 1000 with a 25-bit modulus, you can do the naive loop over ulong's (there will be no overflow because `1000 * 2**50 < 2**64`) and just one modular reduction at the very end. But the compiler does not know that because our modulus is 25 bits, the entries we multiply fit in 32 bits, so it can actually use 32-bit multiplication to get 64-bit products (e.g. avx2  `_mm256_mul_epu32`). I suppose we could give it some hints, by using some casts to uint, but this would still require to add cases and hope that the compiler does what we want it to do.

To be less dot-product-centric, you can have a look at works such as the following: many ways to best exploit vectorization in modular computations are presented, for which I doubt the compiler can often arrive at a similarly efficient solution.
https://arxiv.org/pdf/1407.3383
https://hal.science/hal-02552673/document

All in all, yes if no one complains, I think we could close this issue. And at the same time, since I have started some work on an integer version of the nmod FFT, I will keep Edgar's suggestion in mind and try to get a better understanding of whether we need explicit vectorization in these specific algorithms.

**Comment by edgarcosta** [comment]
I agree with everything you said.
