### ISSUE TITLE
License change to GMP-compatible license

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1763]
It would be nice to be able to copy GMP- and MPFR-code for use in FLINT. For example, it would be advantageous to use GMP's `mpn_addmul_1` assembly code to generate `mpn_mulhigh_basecase`, used for fast floating point arithmetic and integer division.

**Comment by edgarcosta** [comment]
What are the advantages/disadvantages?
As far as I understand, LGPLv3 is not backward compatible with LGPL v2.1.
Furthermore, LGPLv3 makes it harder for proprietary software to use the library.
I believe these two are the reasons why NTL is distributed under LGPLv2.1+ and Magma decided to keep using old versions of GMP http://magma.maths.usyd.edu.au/magma/faq/thirdparty

**Comment by albinahlback** [comment]
> What are the advantages/disadvantages?

An advantage is that we can use their code in our codebase and perhaps improve it further. Moreover, as they are our only two mandatory dependencies and we keep the same interface as them, I think it is pretty natural that we have a compatible license.

> As far as I understand, LGPLv3 is not backward compatible with LGPL v2.1.

In what sense? My license knowledge is not the best.

> Furthermore, LGPLv3 makes it harder for proprietary software to use the library.

That is true, but the same goes for GMP and MPFR.

**Comment by edgarcosta** [comment]
> In what sense? My license knowledge is not the best.

I believe that the library cannot automatically be re-licensed under LGPL v3 without the consent of all copyright holders.

**Comment by fredrik-johansson** [comment]
> > In what sense? My license knowledge is not the best.
> 
> I believe that the library cannot automatically be re-licensed under LGPL v3 without the consent of all copyright holders.

FLINT is licensed LGPL version 2.1 "or any later version" which implies that such re-licensing is permitted.

**Comment by jrick** [comment]
> > > In what sense? My license knowledge is not the best.
> > 
> > 
> > I believe that the library cannot automatically be re-licensed under LGPL v3 without the consent of all copyright holders.
> 
> FLINT is licensed LGPL version 2.1 "or any later version" which implies that such re-licensing is permitted.

this isn't really true.  as a consumer of the library, you can interpret it to give you the rights of lgpl3+, but you can't force the license switch and force everyone to give up the rights to use it under lgpl2.

this is actually the primary reason why the gnu project requires copyright assignment (to them), so they are the sole copyright holder and were able to upgrade gpl2+ projects to gpl3+.  You could still interpret the old licenses as giving you the rights of gpl3+ if they did not make any licensing changes, but they wanted to remove the ability to continue using it under the terms of gpl2.

what would have made more sense here, if a full relicensing change was not possible logistically, would be to require lgpl3+ for new contributions going forward.  (but this is probably a moot point, since older releases are still going to be available under lgpl2+.)
