### ISSUE TITLE
polynomials, matrices over groups

### ISSUE THREAD

**Issue by mezzarobba** [flintlib/flint#1868]
```
sage: R = F.UnivariatePolynomialRing(F.SymmetricGroup(3), 'x')
sage: R.is_ring()
True
sage: F.MatrixSpace(F.SymmetricGroup(3), 2, 2).is_ring()
True
```
(Sorry for the Sage syntax, I hope it is transparent enough.)

I am not sure if the issue is that `gr_ctx_init_gr_poly` (resp `...matrix_space`) succeeds (but it returns `void`, so probably not?) or that Flint thinks the result is a ring.

**Comment by fredrik-johansson** [comment]
Indeed, is_ring() returns T_TRUE for the symmetric group. The problem is that is_ring() defaults to T_TRUE and needs to be overridden otherwise, but I overlooked doing this for ``perm``.

A quick fix is to do this overload for ``perm``; the more proper fix is to default is_ring() to T_UNKNOWN and overload it for all actual rings.

**Comment by edgarcosta** [comment]
`T_UNKNOWN` as default sounds a better approach
