### ISSUE TITLE
AVX and nmod

### ISSUE THREAD

**Issue by Sander80** [flintlib/flint#2042]
Greetings!
The "what's new section says 

> The new fft_small module implements FFTs modulo word-size primes and multiplication based on such FFTs. This module requires AVX2 or NEON vector instructions and will not be built on targets that do not support them. The small-prime FFT speeds up the following functions for huge input, sometimes by a factor 2x to 10x

If I look at the documentation of fft_small, it does not look complete (https://flintlib.org/doc/fft_small.html)

I would expect that for example nmod_vec could use the avx speedup, but the code inside is 

```
    if (mod.norm)
    {
        for (i = 0 ; i < len; i++)
        res[i] = _nmod_add(vec1[i], vec2[i], mod);
    } else
    {
        for (i = 0 ; i < len; i++)
        res[i] = nmod_add(vec1[i], vec2[i], mod);
    }
```

and  it does not seem to be ready for vectorization.

So is nmod supposed to gain from vectorization now or is it in the plans?

Thank you!

**Comment by albinahlback** [comment]
If you use the right compiler flags it will utilize AVX if it is available.

Do you get another assembler output that contradicts this?

**Comment by Sander80** [comment]
No assembly yet or performance, just reading the docs and the code.

Since I personally have been plaing a lot with simd optimization, I've been execting to see intel intrinsics or pragma openmp simd or some other techincs and found none of those. Is everything purely done by the compiler?

So what would you suggest to do to get avx working (apart from compiling with avx support)? Should I use nmod_vec? Or any cycle with adding aligned nmod should work?

**Comment by albinahlback** [comment]
> No assembly yet or performance, just reading the docs and the code.

Alright. Anyway, we rely heavily on vectorizable code for some `nmod_vec` functions, of which `nmod_vec_add` is one of them.

> Since I personally have been plaing a lot with simd optimization, I've been execting to see intel intrinsics or pragma openmp simd or some other techincs and found none of those. Is everything purely done by the compiler?

Yes. I hope that it is okay that I give some advice when it comes to this: It is always easier to write the code at a higher level and let the compiler do the rest. Sometimes, you have to really guide the compiler (like `__builtin_unreachable` or write the code differently). Other times, however, the compiler is not that clever and you have to either write it via intrinsics, inline assembly or pure assembly. We do all of this in FLINT, but a lot of this can improve. However, for `nmod_vec_add` I believe it is close-to optimal, at least on with my setup.

> So what would you suggest to do to get avx working (apart from compiling with avx support)? Should I use nmod_vec? Or any cycle with adding aligned nmod should work?

You have to know what you really want, and for that you need to know the hardware. To illustrate what not-to-do: suppose you wish to vectorize something like
```c
void vec_div(long * rp, const long * ap, const long * bp, int n)
{
    int ix;

    for  (ix = 0; ix < n; ix++)
        rp[ix] = ap[ix] / bp[ix];
}
```
on an x86 system. Well, this is not possible since no vectorized integer division exists on x86 (yet).

**Comment by Sander80** [comment]
I see, thank you. I will try to upgrade, rebuild with avx support, switch from cycles of nmod to nmod_vec and measure performance. I will let know what happens

**Comment by Sander80** [comment]
I could not yet dive into assembly or rewrite the code with nmod_vector, but recompiling with avx did not give any speed effect.

Would you expect that a manual cycle

```
for (size_t i = 0; i != MPRIME; ++i) {
   result.N[i] = nmod_add(c1.N[i], c2.N[i], common::flint_mod);
}
```

where N is a class member (unsigned long long N[MPRIME];) and MPRIME is preprocessor-defined (a compile-time constant) should be able to produce AVX?
Or should I try and switch to nmod_vec (which does not seem pleasant due to an extra memory allocation and the need to handle it)?

**Comment by albinahlback** [comment]
I will close this. I will reopen if you can show me that it is not being vectorized.

**Comment by Sander80** [comment]
I see, thank you. I just wanted to get sure it is not something special in the nmod_vec class, but the compiler magic instead. We will give it a try!
